#发布-生产环境-提交企业微信审批
- name: deploy_helm_prod
  image: harbor.example.cn/drone-plugin/drone-weixin:0.1
  pull: always
  #environment:
  #  corpid:
  #    from_secret: wechat_corpid
  #  corp_secret:
  #    from_secret: wechat_corp_secret_approval
  settings:
    corpid: 
    corp_secret: Cj41NiPNRMpFBeu37AOBMMrUO0uI_kkDzws9c0aD3to
    template_id: Bs5NGcoanqFkaE8p4sJkVaD84bf2vyo3qhWDPnhiX
    registry_name: harbor.example.cn
    image_tag: ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_BRANCH}
    creator_userid: WangRuiHua
  #commands:
  #  - cat /drone/src/.scannerwork/report-task.txt
  when:
    branch:
      - master
